name: Deploy GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: true

      - name: Run build
        run: pnpm build

      - name: Start serve process
        run: |
          pnpm serve &
          echo $! > process.pid
        shell: bash

      - name: Wait for server to start
        run: sleep 5

      - name: Make wget request and save to index.html
        run: wget -O index.html http://localhost:3000

      - name: Make wget request and save to microservice-api.html
        run: wget -O microservice-api.html http://localhost:3001

      - name: Stop process
        run: kill $(cat process.pid)
        shell: bash

      - name: Remove default proxy
        run: sed -i -e 's#data-proxy-url="https://proxy.scalar.com"##g' index.html
        shell: bash

      - name: Remove default proxy
        run: sed -i -e 's#data-proxy-url="https://proxy.scalar.com"##g' microservice-api.html
        shell: bash

      - name: Move to dist
        run: |
          mkdir dist
          mv tsp-output/schema/* dist/
          mv index.html dist/
          mv microservice-api.html dist/

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
